### ISSUE TITLE
Make the Web Version work with the Kobo Browser

### ISSUE THREAD

**Issue by folkemat** [pgaskin/kepubify#77]
I can easily download .epubs with the Kobo Browser. Only for converting them to Kepub I have to gab either a PC or mobile phone. Is there a way or any plan to make the Web Version of Kepubify compatible with the Kobo Browser, so that one need 0 extra devices to get a book? Currently, you get an error message that the browser is not supported.

**Comment by pgaskin** [comment]
That's not happening for multiple reasons, unfortunately. For one, the open file dialog causes the Kobo to hang since event handling for it isn't implemented. Most importantly, though, webkit on it is so hopelessly out of date, and some devices barely have enough RAM for anything, that I'm not even sure I could make it run slowly.
