### ISSUE TITLE
Feature Request: Specify an encoding with command line arguments

### ISSUE THREAD

**Issue by ss7m** [pgaskin/kepubify#82]
Often times I find myself converting epubs with text that uses a lot of unicode characters (for instance books in Spanish) but that don't actually specify the encoding in the xhtml documents within the epub. This results in a kepub file where any text that uses accents gets turned into illegible characters. Currently the way I have to fix this is unzipping the epub, adding in the encoding to the xhtml documents, and then re-zipping. It would be nice to be able to just invoke kepubify with something like

    kepubify --encoding utf-8 MyEpub.epub

to force kepubify into a particular encoding.

**Comment by BillyGrande** [comment]
Yeah, I made a post about it, some hours ago https://www.reddit.com/r/kobo/comments/soloqp/kepubify_punctuation_problem/
Probably an easy fix.

**Comment by asb** [comment]
I'm seeing this same issue when converting a retail copy of All Systems Red. The first chapter is fine, but the second has corrupted characters instead of quotation markets / apostrophes. Both first and second chapters have `<meta content="application/xhtml+xml; charset=utf-8" http-equiv="default-style"/>`, but I haven't investigated more than that.
