### ISSUE TITLE
UTF-8 conversion issue with particular input

### ISSUE THREAD

**Issue by asb** [pgaskin/kepubify#83]
I mentioned this in #82, but on reflection I believe this is a separate bug.

For the [attached reproducer](https://github.com/pgaskin/kepubify/files/8193325/repro.epub.zip) (cut down from All Systems Red - removed all copyrighted content, leaving just the first paragraph of chapter 1 and first paragraph of chapter 2):
```
mv repro.epub.zip repro.epub
kepubify repro.epub
```
If you then inspect the result, you'll see ch02.xhtml now contains `hadnâ€™t` rather than `hadn’t`. It's not clear why this happens for ch02 and not ch01 - both are marked as UTF-8 with `<meta content="application/xhtml+xml; charset=utf-8" http-equiv="default-style"/>`.

**Comment by pgaskin** [comment]
That meta tag is utter garbage... `default-style` has nothing to do with the content type.

I think I will partially revert the change I did in v4.0.2 and put it behind a flag to detect the charset, since apparently, more people have UTF-8 EPUBs which don't declare their charset properly than people who have non-compliant non-UTF-8 EPUBs.

**Comment by asb** [comment]
Thanks for pointing that out - I'd missed that. Presumably there's some charset detection going on somewhere, as that would explain why ch01 is fine but not ch02.

**Comment by asb** [comment]
Thank you for such a rapid fix, and of course for providing kepubify in the first place.
